// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressesController from "./addresses_controller"
application.register("addresses", AddressesController)

import CitizensController from "./citizens_controller"
application.register("citizens", CitizensController)

import HomeController from "./home_controller"
application.register("home", HomeController)

import MasksController from "./masks_controller"
application.register("masks", MasksController)
