require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-factory_bot
  - rubocop-capybara
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  TargetRailsVersion: 7.0
  Exclude:
    - bin/**/*
    - tmp/**/*
    - db/schema.rb
    - db/seeds.rb
    - config/environments/**/*
    - vendor/**/*
    - tmp/**/*

Lint/MissingSuper:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/routes.rb
    - config/initializers/form_ease_bootstrap.rb

RSpec/Rails/NegationBeValid:
  EnforcedStyle: be_invalid

RSpec/PendingWithoutReason:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false
