default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["POSTGRES_HOST"] %>
  username: <%= ENV.fetch("POSTGRES_USER", "rails_challenge") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "S4hc1bJ5u78O7yn0do1Y563J07I") %>
  pool: <%= ENV.fetch("POSTGRES_POOL", 5) %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "rails_challenge_development") %>

test:
  <<: *default
  database: rails_challenge_test
